### ISSUE TITLE
nav not working in chrome app

### ISSUE THREAD

**Issue by musamusa** [eHealthAfrica/LMIS-Chrome#1]
@adothompson nav settings works great in chrome and Firefox but not as chrome app, I checked the console to see why and I saw this:

Can't open same-window link to "unsafe:chrome-extension://pbgmdkppjbeghgibmackjiifimgdfhhk/index.html#/settings"; try target="_blank".

it throws that up any time I click on the links with templates (home, settings)
maybe  its just on my system, but I'm trying to figure out why and how to fix it.

**Comment by adothompson** [comment]
Fixed by white-listing chrome-extension in app.js for now.  I have not added the csp relevant tags since these break a stuff now.  There is a lot of chrome security settings we'll have to sort out before publishing. 

```
angular.module('lmisChromeApp')
    .config(['$compileProvider', function($compileProvider) {
        $compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|chrome-extension):/);
    }]);
```
