### ISSUE TITLE
create summary sheet data inside of lomis KPI module

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Chrome#564]
create a workflow, similar to the lomis vaccine counters, that the HF worker can put in summary information by categories captured on the summary sheet  (e.g., Penta 14 weeks to 11 months , Penta 12 months to 24 months) https://docs.google.com/a/ehealthnigeria.org/document/d/1FsP9lA3Rj2rRixmsk3JHP-417YadTwDTgXYD9G6n7mo/edit

**Comment by janetbutts** [comment]
https://drive.google.com/drive/u/0/#search?q=summary

**Comment by musamusa** [comment]
same as Pull Request https://github.com/eHealthAfrica/LMIS-Chrome/pull/574
