### ISSUE TITLE
fix map on lomis dev dashboard

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Chrome#573]

**Comment by freefony** [comment]
This seem to be an issue with the data, missing fields most likely, rather the codes itself. so i will inspect the data to see what disparity there might be. As at now the map is rendered properly.

**Comment by janetbutts** [comment]
Tested it. Looks good. Thanks!

**Comment by freefony** [comment]
I can't move this ticket to "Done" yet as we still need to know what in the data might be throwing it off.
