### ISSUE TITLE
Update, improve and refactor LoMIS Dispatch Repo

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Chrome#579]

**Comment by jofomah** [comment]
@janetbutts, am updating this to the following:
1. Add documentation.
2. Move configuration details from code to config file.
3. Add unit tests.
4. Refactor code.
5. Add persistent logging capability.

**Comment by jofomah** [comment]
@janetbutts Completed and available at https://github.com/eHealthAfrica/dispatch/pull/6
