### ISSUE TITLE
stock chart displays incorrectly

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/LMIS-Chrome#580]
Chart displays a stock out when there inventory is displayed in the list of products on the review screen
See:
https://drive.google.com/a/ehealthnigeria.org/file/d/0Bw4ZOU53BOuXSGxGazMyUVhOQWNyOE12aWszd0lXSTVTQkdj/view?usp=sharing
https://drive.google.com/a/ehealthnigeria.org/file/d/0Bw4ZOU53BOuXbFZSbUMyRWhjYzZOTXEwSkI1MVp5a1VwWkVj/view?usp=sharing

**Comment by musamusa** [comment]
@janetbutts, the fix require updating the app config 'bw' target population field for the affected facility , that’s what I did, still waiting for confirmation from Yusuf  before closing cc @jofomah
